### ISSUE TITLE
valinet-systray-battery-brightness.wh.cpp does not work for me

### ISSUE THREAD

**Issue by Anixx** [valinet/wh-mods#1]
The sound change on scrolling icon works but the battery brightness mod does not. It does not work either with the Win7-style power flyout or with Win10 style. I use the Win10 tskbar.

**Comment by valinet** [comment]
It uses the `highlevelmonitorconfigurationapi.h` APIs, which only changes the brightness on desktop monitors, not laptops, take that into account. Otherwise idk, works fine on my end.

**Comment by Anixx** [comment]
Thanks for the clarification, I indeed have a laptop.

**Comment by Anixx** [comment]
Close

**Comment by valinet** [comment]
For laptops, it could press the brightness keys instead (the sound change one does something along these lines), idk exactly how to do that for brightness but could look into it at some point. On laptops you usually have physical buttons that allow you to change the brightness, so it is less of an issue imo.
